name: release

on: 
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  Build:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: bash release.sh ${{ github.ref }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: |
            dist/*.bobplugin
        env:
          GITHUB_TOKEN: ${{ secrets.GT_Token }}
      
      - run: rm -rf dist

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: new release!
      